name: smart_form_x
description: AI-powered form engine for Flutter.
version: 0.1.0

topics:
  - dart
  - flutter
  - forms
  - mobile
  - pub
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/NPM-Packages-Modules/flutter
homepage: https://github.com/NPM-Packages-Modules/flutter/tree/main/smart_form_x
issue_tracker: https://github.com/NPM-Packages-Modules/flutter/issues
